### ISSUE TITLE
stack corruption detected (-fstack-protector)

### ISSUE THREAD

**Issue by KORuL** [baresip/rem#120]
https://github.com/juha-h/baresip-studio/issues/296

**Comment by KORuL** [comment]
in function
sa_ntop
or
net_add_address_ifname
or related to filling
struct sa temp_sa

**Comment by KORuL** [comment]
when the network changes in a mobile application, a crash occurs after calling a function from the library

**Comment by sreimers** [comment]
Please avoid to open duplicate issues! These functions are not rem related.
