### ISSUE TITLE
New rem release?

### ISSUE THREAD

**Issue by robert-scheck** [baresip/rem#31]
Is there any chance for a new rem release? There recently was re v2.1.0 and baresip v2.0.0 also seems to be around the corner.

**Comment by sreimers** [comment]
Yes we prepare a new release and align the version number with re and baresip.

**Comment by robert-scheck** [comment]
Closing due to the existence of tag [v2.0.0](https://github.com/baresip/rem/releases/tag/v2.0.0) - thank you.
